name: Code deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private-key.pem
        chmod 600 ~/private-key.pem
    - name: Create SSH directory
      run: |
        mkdir -p ~/.ssh
    - name: Add known host
      run: |
        ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts    
    - name: connect and pull
      run: ssh -i ~/private-key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
